<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Author>kruft</Author>
		<Product>ShipCam Pro</Product>
		<Version>0.3.0</Version>
		<Description>Saves the 3rd-person toggle state and allows the camera to zoom, wrap around, and lock in place.</Description>
		<Categories>mod;client-side</Categories>
	</PropertyGroup>
	<ItemGroup>
		<ModReference Include="BepInEx-BepInExPack_LostSkies" Version="6.0.75301" />
	</ItemGroup>
	<Import Project="../LostSkies.targets" />
</Project>